/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSDictionary, NSString, UIViewController;

@interface BatteryUsageRadarComposeViewController : NSObject <UIAlertViewDelegate>
{
    UIViewController *_parentViewController;
    NSDictionary *_currentDictionary;
}

+ (_Bool)hasRadarCompose;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSDictionary *currentDictionary; // @synthesize currentDictionary=_currentDictionary;
- (id)initWithParentView:(id)arg1 andDictionary:(id)arg2;
@property(retain, nonatomic) UIViewController *parentViewController; // @synthesize parentViewController=_parentViewController;
- (void)showRadarComposeAlert;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

