/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "BatteryUIController.h"

@interface BatteryUIController (DemoSupport)
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)getDemoName:(id)arg1;
- (_Bool)inDemoMode;
- (void)savePList:(id)arg1;
@end

