/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "BatteryUIController.h"

@interface BatteryUIController (UsageTimeSupport)
- (void)_fullyChargedStateChanged;
- (void)_pluggedInStateChanged;
- (id)_standbySpecifier;
- (id)_textSpecifier;
- (id)_usageSpecifier;
- (void)initUsageTimeNotifications;
- (void)resumeUsageTimeNotifications;
- (_Bool)shouldShowTime;
- (id)standbyElapsed:(id)arg1;
- (void)startTimer;
- (void)stopTimer;
- (void)stopUsageTimeNotifications;
- (void)update:(id)arg1;
- (void)updateUsageTimeUI:(_Bool)arg1;
- (id)usageElapsed:(id)arg1;
- (id)usageTimeSpecifierArray;
@end

