/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSOperationQueue, NSString;

@interface BatteryUsageQueryModule : NSObject
{
    NSOperationQueue *_queryUsageQueue;
    NSOperationQueue *_queryModelQueue;
    int _type;
    NSString *_manualFileName;
    NSArray *_graphNames;
}

+ (id)sharedModule;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *graphNames; // @synthesize graphNames=_graphNames;
- (id)init;
@property(retain, nonatomic) NSString *manualFileName; // @synthesize manualFileName=_manualFileName;
- (void)populateBatteryModelsWithCompletion:(id)arg1;
- (void)populateBatteryUsageWithCompletion:(id)arg1;
@property(nonatomic) int type; // @synthesize type=_type;

@end

