/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "BatteryUIController.h"

@interface BatteryUIController (SuggestionsSupport)
- (id)_suggestionEntries;
- (id)_suggestionGroupSpecifier;
- (void)generateSuggestionsEntrySpecifiers:(id)arg1;
- (id)screenLock:(id)arg1;
- (void)setScreenLock:(id)arg1 specifier:(id)arg2;
- (void)updateSuggestionsSpecifiers;
@end

