/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@class BatteryUsageRadarComposeViewController, NSDictionary, UIActivityIndicatorView, UIScrollView;

@interface BatteryUIGraphsViewController : UIViewController
{
    NSDictionary *_currentDictionary;
    UIScrollView *_rootScrollView;
    UIActivityIndicatorView *_activityIndicator;
    BatteryUsageRadarComposeViewController *_radarController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(retain, nonatomic) BatteryUsageRadarComposeViewController *radarController; // @synthesize radarController=_radarController;
- (void)reportIssue;
@property(retain, nonatomic) UIScrollView *rootScrollView; // @synthesize rootScrollView=_rootScrollView;
- (void)setUpModelingView:(id)arg1;
- (_Bool)validateDictionary:(id)arg1;
- (void)viewDidLoad;

@end

