/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSListController.h"

@class NSDictionary;

@interface BatteryUIDetailController : PSListController
{
    NSDictionary *_appEntry;
}

- (void).cxx_destruct;
- (id)getSortValueForKey:(id)arg1;
- (id)getValueForSpecifier:(id)arg1;
- (id)specifiers;

@end

