/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSDate, NSMutableArray;

@interface PLBatteryUIGraphView : UIView
{
    NSDate *startDate;
    NSDate *endDate;
    float maxPower;
    float minPower;
    int _errValue;
    int _graphType;
    NSMutableArray *_inputData;
}

+ (int)graphHeight;
- (void).cxx_destruct;
- (void)drawErrorText:(struct CGContext *)arg1 andRect:(struct CGRect)arg2;
- (void)drawGrid:(struct CGContext *)arg1 andRect:(struct CGRect)arg2;
- (void)drawPoints:(struct CGContext *)arg1 andRect:(struct CGRect)arg2;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) int graphType; // @synthesize graphType=_graphType;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andData:(id)arg2;
@property(copy, nonatomic) NSMutableArray *inputData; // @synthesize inputData=_inputData;
- (void)setDefaultRange;
- (void)setRangesFromArray:(id)arg1;

@end

