/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PSTableCell.h"

@interface PLBatteryUIDisplayTableCell : PSTableCell
{
    int _type;
    id <PLBatteryUIDisplayTableCellDelegate> _delegate;
}

+ (long long)cellStyle;
- (void).cxx_destruct;
- (_Bool)canReload;
@property(nonatomic) __weak id <PLBatteryUIDisplayTableCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)refreshCellContentsWithSpecifier:(id)arg1;

@end

