/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "PSHeaderFooterView.h"

@class NSNumber, NSString, UILabel;

@interface PLBatteryUIBatteryGroupHeader : UIView <PSHeaderFooterView>
{
    NSString *_rangeString;
    NSNumber *_cycles;
    UILabel *_batteryChargeCyclesString;
}

+ (id)headerViewWithRange:(id)arg1 Cycles:(id)arg2;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 range:(id)arg2 cycles:(id)arg3;
- (id)initWithSpecifier:(id)arg1;
- (void)layoutSubviews;
- (void)setCycle:(id)arg1;
- (void)setRange:(id)arg1;

@end

