/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "PSHeaderFooterView.h"

@class NSString, UIActivityIndicatorView, UILabel;

@interface PSHeaderSpinnerCell : UIView <PSHeaderFooterView>
{
    UILabel *_text;
    UIActivityIndicatorView *_spinner;
    _Bool _animating;
    NSString *_name;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
- (id)initWithSpecifier:(id)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (double)preferredHeightForWidth:(double)arg1;
@property(readonly) UIActivityIndicatorView *spinner;

@end

